server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
name: penchengcheng
student:
  name: pcc
  age: 26
spring:
  mvc:
    view:
      prefix: /WEB_INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://****/****
    username: *****
    password: *****
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update