server:
  port: 8081
name: penchengcheng
student:
  name: pcc
  age: 26
spring:
  mvc:
    view:
      prefix: /WEB_INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://10.32.16.108:3306/***
    username: ***
    password: ***
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
